### ISSUE TITLE
Unable to load in .NET Core 2.0

### ISSUE THREAD

**Issue by Latency** [reflectsoftware/ReflectInsight.Extensions.Logging#4]
Unable to load in .NET Core since App.Domains do not exist.

Try removing all occurrences for this and rework the loading of the ReflectInsight.Config from the main library (which isn't even fully supported for .NET CORE as reference dependency.

```
System.TypeInitializationException occurred
  HResult=0x80131534
  Message=The type initializer for 'ReflectSoftware.Insight.ReflectInsightConfig' threw an exception.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at ReflectSoftware.Insight.ReflectInsightConfig.get_Control()
   at ReflectInsight.Extensions.Logging.ReflectInsightLoggerProvider..ctor(String configFile) in D:\Documents\Visual Studio 2017\Projects\ReflectInsight.Extensions.Logging\src\ReflectInsight.Extensions.Logging\ReflectInsightLoggerProvider.cs:line 22
   at ReflectInsight.Extensions.Logging.ReflectInsightLoggerFactoryExtensions.AddReflectInsight(ILoggerFactory factory, String configFile) in D:\Documents\Visual Studio 2017\Projects\ReflectInsight.Extensions.Logging\src\ReflectInsight.Extensions.Logging\ReflectInsightLoggerFactoryExtensions.cs:line 22
   at Test.Program1.Main(String[] args) in D:\Documents\Visual Studio 2017\Projects\TinTin#\Test\Program1.cs:line 18

Inner Exception 1:
TypeInitializationException: The type initializer for 'ReflectSoftware.Insight.ReflectInsightService' threw an exception.

Inner Exception 2:
TypeInitializationException: The type initializer for 'ReflectSoftware.Insight.RIExceptionManager' threw an exception.

Inner Exception 3:
MissingMethodException: Method not found: 'System.AppDomainSetup System.AppDomain.get_SetupInformation()'.

```

**Comment by codematrix** [comment]
Hi @latency because this nuget package uses Reflectsoftware.Insight nuget it only supports .net core full framework.

**Comment by Latency** [comment]
Are we talking about configuring for multi-support here?  in the *.csproj file... ?

`    <TargetFrameworks>net47;netcoreapp2.0;netstandard2.0</TargetFrameworks>`

**Comment by codematrix** [comment]
As stated, the ReflectInsight nuget package which is used by the ReflectInsight.Extensions.Logging will compile but it will cause runtime errors because parts the references that it requires are not supported by all runtime frameworks you mentioned.  Changing the ReflectInsight will be challenging as underlying framework dependencies will fail to execute, as you have already detected.

We can change how the library loads the configuration file, but other parts of the library will also fail to execute. We tried to convert RI using .netcore2. and .netstandard2.0 but ran into compile errors as parts of the those frameworks no longer support parts of the classic runtime.

We do have plans to support this at a later date by removing suspect code paths that will no longer work in the newer frameworks. 

Keep in mind the ReflectInsight.Extensions.Logging is just a wrapper to invoke the RI API.

**Comment by Latency** [comment]
Okay, I appreciate your guys's efforts and saving me the time in trying to run it on my own.

Thank you!
